apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing
  labels:
    app: testing
  namespace: testautomateddeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing
  template:
    metadata:
      labels:
        app: testing
    spec:
      containers:
        - name: testing
          image: harshaacrregistry.azurecr.io/testimageautomateddeployment:latest
          ports:
            - containerPort: 5000