apiVersion: v1
kind: Service
metadata:
  name: testing
  namespace: testautomateddeployment
spec:
  type: LoadBalancer
  selector:
    app: testing
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000