apiVersion: v1
kind: Service
metadata:
  name: tests
  namespace: namespace-workflow-1706740484111
spec:
  type: LoadBalancer
  selector:
    app: tests
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000